export const blogPosts: BlogPost[] = [
  {
    id: "1",
    slug: "amazon-a-plus-content-guide",
    title: "The Ultimate Guide to Amazon A+ Content: Design, Strategy, and Conversion",
    excerpt: "In today's competitive e-commerce world, standing out on Amazon isn't just about having a great product it's about how you present it...",
    content: `...`,
    author: "Prince Rajput",
    date: "2024-01-15",
    readTime: "2 min read",
    image: "https://i.ibb.co/nM8vdHFy/Whats-App-Image-2025-11-11-at-4-59-06-PM.jpg",
    image1: "https://i.ibb.co/bk0wmtQ/Whats-App-Image-2025-11-11-at-4-59-06-PM-1.jpg",
    category: "E-commerce Strategy",
    tags: ["E-commerce", "Mistakes", "Conversion", "SEO"],
    keywords: [
      "Amazon A+ Content",
      "Enhanced Brand Content", 
      "Amazon A+ Content Guide",
      "Amazon A+ Content Optimization",
      "A+ Content Amazon Tips",
      "Amazon product listing",
      "E-commerce optimization",
      "Amazon seller tips"
    ]
  },
  {
    id: "2",
    slug: "sales-performance-analytics",
    title: "The Power of Data: Using Sales Performance Analytics to Double Your Revenue",
    excerpt: "Discover how sales performance analytics can transform your business growth...",
    content: `...`,
    author: "Bhupinder Singh",
    date: "2024-01-12",
    readTime: "2 min read",
    image: "https://i.ibb.co/93S0cftc/Blg-2.png",
    category: "AI Technology",
    tags: ["AI", "Technology", "Personalization", "Future"],
    keywords: [
      "Sales performance analytics",
      "Sales data analysis",
      "Sales analytics for e-commerce",
      "Revenue growth strategies",
      "Data-driven sales optimization",
      "E-commerce analytics",
      "Business intelligence",
      "Sales metrics"
    ]
  },
  {
    id: "3",
    slug: "easy-category-approval-guide",
    title: "The Easiest Way to Get Category Approval for Restricted Items (Amazon/Flipkart)",
    excerpt: "Learn the easiest way to get category approval for restricted items on Amazon and Flipkart...",
    content: `...`,
    author: "Bhupinder Singh",
    date: "2024-01-10",
    readTime: "1 min read",
    image: "https://i.ibb.co/5X3ZVGxB/blog-3.png",
    category: "Mobile Commerce",
    tags: ["Mobile", "Statistics", "Trends", "Shopping"],
    keywords: [
      "Amazon category approval",
      "Flipkart category approval",
      "Restricted category approval Amazon",
      "Restricted items approval Flipkart",
      "Amazon seller category approval process",
      "Flipkart seller onboarding requirements",
      "E-commerce seller registration",
      "Online selling approval"
    ]
  },
  {
    id: "4",
    slug: "mobile-ecommerce-conversion-strategies",
    title: "From Visitor to Buyer: How to Optimize Your Mobile E-commerce Sales",
    excerpt: "Learn how to turn mobile visitors into loyal buyers with proven optimization strategies...",
    content: `...`,
    author: "Prince Rajput",
    date: "2024-01-08",
    readTime: "2 min read",
    image: "https://i.ibb.co/svPtC4Wm/Blog-4.png",
    category: "Social Media",
    tags: ["Social Media", "Instagram", "TikTok", "Influencers"],
    keywords: [
      "mobile e-commerce optimization",
      "mobile e-commerce conversions",
      "mobile conversion rate optimization",
      "optimize mobile online store",
      "mobile shopping optimization",
      "mobile e-commerce sales strategies",
      "responsive e-commerce design",
      "mobile-first e-commerce"
    ]
  },
  {
    id: "5",
    slug: "seller-account-setup-amazon-filpkart",
    title: "Step-by-Step: Setting Up Your First E-commerce Seller Account (Amazon/Flipkart)",
    excerpt: "Complete guide to creating your first seller account on Amazon and Flipkart...",
    content: `...`,
    author: "Prince Rajput",
    date: "2024-01-05",
    readTime: "2 min read",
    image: "https://i.ibb.co/Xxt1PvNR/blog-5.png",
    category: "SEO",
    tags: ["Voice Search", "SEO", "Optimization", "Technology"],
    keywords: [
      "How to create Amazon seller account",
      "How to create Flipkart seller account",
      "Amazon seller registration guide",
      "Flipkart seller registration process",
      "Start selling on Amazon India",
      "Start selling on Flipkart India",
      "E-commerce account setup",
      "Online selling guide"
    ]
  },
  {
    id: "6",
    slug: "5-minute-product-listing-audit",
    title: "The 5-Minute Product Listing Audit: Boost Your Conversion Rate by 50%",
    excerpt: "Learn how to perform a quick 5-minute product listing audit that can boost your conversion rates...",
    content: `...`,
    author: "Bhupinder Singh",
    date: "2024-01-03",
    readTime: "3 min read",
    image: "https://i.ibb.co/FkHnKDZh/Blog-6.png",
    category: "Customer Experience",
    tags: ["Reviews", "Trust", "Conversion", "Feedback"],
    keywords: [
      "product listing audit",
      "e-commerce product listing optimization",
      "boost conversion rate",
      "product page optimization",
      "Amazon product listing audit",
      "Flipkart product listing optimization",
      "E-commerce SEO",
      "Product listing best practices"
    ]
  }
]